package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class GradeAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGradeAllPropertiesEquals(Grade expected, Grade actual) {
        assertGradeAutoGeneratedPropertiesEquals(expected, actual);
        assertGradeAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGradeAllUpdatablePropertiesEquals(Grade expected, Grade actual) {
        assertGradeUpdatableFieldsEquals(expected, actual);
        assertGradeUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGradeAutoGeneratedPropertiesEquals(Grade expected, Grade actual) {
        assertThat(actual)
            .as("Verify Grade auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGradeUpdatableFieldsEquals(Grade expected, Grade actual) {
        assertThat(actual)
            .as("Verify Grade relevant properties")
            .satisfies(a -> assertThat(a.getScore()).as("check score").isEqualTo(expected.getScore()))
            .satisfies(a -> assertThat(a.getRemarks()).as("check remarks").isEqualTo(expected.getRemarks()))
            .satisfies(a -> assertThat(a.getDateAwarded()).as("check dateAwarded").isEqualTo(expected.getDateAwarded()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGradeUpdatableRelationshipsEquals(Grade expected, Grade actual) {
        assertThat(actual)
            .as("Verify Grade relationships")
            .satisfies(a -> assertThat(a.getStudent()).as("check student").isEqualTo(expected.getStudent()))
            .satisfies(a -> assertThat(a.getSubject()).as("check subject").isEqualTo(expected.getSubject()));
    }
}
